name: Android Auto Built Snapshot Apk CI

on: 
  push:
    paths-ignore:
      - '**.md'
      - '**.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Set NDK
      uses: nttld/setup-ndk@v1
      with:
       ndk-version: r27
       local-cache: true
    - run: ndk-build NDK_PROJECT_PATH=/home/runner/work/moonlight-next/ APP_BUILD_SCRIPT=/home/runner/work/moonlight-next/app/src/main/jni/Android.mk NDK_APPLICATION_MK=/home/runner/work/moonlight-next/app/src/main/jni/Application.mk


    - name: Set Cache
      uses: actions/cache@v3
      with:
        path: |
          build
          app/build
        key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle*', 'gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload NonRoot Artifact
      uses: actions/upload-artifact@v3
      with:
        name: "auto_built_snapshot_nonRoot_${{ github.sha }}.apk"
        path: app/build/outputs/apk/nonRoot/debug/app-nonRoot-debug.apk
        retention-days: 10

    - name: Upload Root Artifact
      uses: actions/upload-artifact@v3
      with:
        name: "auto_built_snapshot_root_${{ github.sha }}.apk"
        path: app/build/outputs/apk/root/debug/app-root-debug.apk
        retention-days: 10